### ISSUE TITLE
15 minutes sync not working?

### ISSUE THREAD

**Issue by FragMenthor** [watkins-matt/home-assistant-google-keep-sync#11]
Hello again. It seams that 0.92 stopped the automated sync every 15 minutes; I did an automation to call the update_entity service every 15 minutes, and it works (also use my cellphone sensors do detect when the app is used / closed and update a little bit after).

```
alias: "Lista de Compras: Sincronizar"
description: ""
trigger:
  - platform: time_pattern
    minutes: /15
    seconds: "10"
    id: padrao_tempo
  - platform: state
    entity_id:
      - sensor.telemovel_fragmenthor_last_used_app
    from: com.google.android.keep
    id: app_fragmenthor
condition: []
action:
  - delay:
      minutes: 1
      seconds: 30
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: todo.google_keep_compras_supermercado
mode: restart
```

Whithout this automation the list would not update on the HA side (waited more than 1 hour and still the items I added in Google Keep would't show up on HA). Is it only me?
By the way, is there a reason for limiting the sync to every 15 minutes? Why not 5 minutes, for instance? I am asking this to try to undertand if I am stepping over some king of limit with my automation.

And a little info needed from my side: where are these lists stored? Can't find them anywere...
Thanks again!
